server:
    port: 80

build_name: @project.name@
build_version: @project.version@

spring:
    datasource:
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
        url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate: 
            ddl-auto: create
        show-sql: true